/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalkinRouteImport } from './routes/walkin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserWalletRouteImport } from './routes/user.wallet'
import { Route as UserTopupRouteImport } from './routes/user.topup'
import { Route as UserSignupRouteImport } from './routes/user.signup'
import { Route as UserSettingsRouteImport } from './routes/user.settings'
import { Route as UserLoginRouteImport } from './routes/user.login'
import { Route as UserHistoryRouteImport } from './routes/user.history'
import { Route as UserDashboardRouteImport } from './routes/user.dashboard'
import { Route as UserComplaintsRouteImport } from './routes/user.complaints'
import { Route as UserBookRouteImport } from './routes/user.book'
import { Route as UserBillsRouteImport } from './routes/user.bills'
import { Route as UserActiveRouteImport } from './routes/user.active'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSitesRouteImport } from './routes/admin.sites'
import { Route as AdminSiteDetailsRouteImport } from './routes/admin.site-details'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminRecordsRouteImport } from './routes/admin.records'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const WalkinRoute = WalkinRouteImport.update({
  id: '/walkin',
  path: '/walkin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserWalletRoute = UserWalletRouteImport.update({
  id: '/user/wallet',
  path: '/user/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTopupRoute = UserTopupRouteImport.update({
  id: '/user/topup',
  path: '/user/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSignupRoute = UserSignupRouteImport.update({
  id: '/user/signup',
  path: '/user/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user/settings',
  path: '/user/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/user/login',
  path: '/user/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserHistoryRoute = UserHistoryRouteImport.update({
  id: '/user/history',
  path: '/user/history',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UserComplaintsRoute = UserComplaintsRouteImport.update({
  id: '/user/complaints',
  path: '/user/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBookRoute = UserBookRouteImport.update({
  id: '/user/book',
  path: '/user/book',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBillsRoute = UserBillsRouteImport.update({
  id: '/user/bills',
  path: '/user/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const UserActiveRoute = UserActiveRouteImport.update({
  id: '/user/active',
  path: '/user/active',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/admin/sites',
  path: '/admin/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSiteDetailsRoute = AdminSiteDetailsRouteImport.update({
  id: '/admin/site-details',
  path: '/admin/site-details',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/admin/search',
  path: '/admin/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecordsRoute = AdminRecordsRouteImport.update({
  id: '/admin/records',
  path: '/admin/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/admin/complaints',
  path: '/admin/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/walkin': typeof WalkinRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-details': typeof AdminSiteDetailsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/active': typeof UserActiveRoute
  '/user/bills': typeof UserBillsRoute
  '/user/book': typeof UserBookRoute
  '/user/complaints': typeof UserComplaintsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/history': typeof UserHistoryRoute
  '/user/login': typeof UserLoginRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/signup': typeof UserSignupRoute
  '/user/topup': typeof UserTopupRoute
  '/user/wallet': typeof UserWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/walkin': typeof WalkinRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-details': typeof AdminSiteDetailsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/active': typeof UserActiveRoute
  '/user/bills': typeof UserBillsRoute
  '/user/book': typeof UserBookRoute
  '/user/complaints': typeof UserComplaintsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/history': typeof UserHistoryRoute
  '/user/login': typeof UserLoginRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/signup': typeof UserSignupRoute
  '/user/topup': typeof UserTopupRoute
  '/user/wallet': typeof UserWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/walkin': typeof WalkinRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-details': typeof AdminSiteDetailsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/active': typeof UserActiveRoute
  '/user/bills': typeof UserBillsRoute
  '/user/book': typeof UserBookRoute
  '/user/complaints': typeof UserComplaintsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/history': typeof UserHistoryRoute
  '/user/login': typeof UserLoginRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/signup': typeof UserSignupRoute
  '/user/topup': typeof UserTopupRoute
  '/user/wallet': typeof UserWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/walkin'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/records'
    | '/admin/requests'
    | '/admin/revenue'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/site-details'
    | '/admin/sites'
    | '/admin/users'
    | '/user/active'
    | '/user/bills'
    | '/user/book'
    | '/user/complaints'
    | '/user/dashboard'
    | '/user/history'
    | '/user/login'
    | '/user/settings'
    | '/user/signup'
    | '/user/topup'
    | '/user/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/walkin'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/records'
    | '/admin/requests'
    | '/admin/revenue'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/site-details'
    | '/admin/sites'
    | '/admin/users'
    | '/user/active'
    | '/user/bills'
    | '/user/book'
    | '/user/complaints'
    | '/user/dashboard'
    | '/user/history'
    | '/user/login'
    | '/user/settings'
    | '/user/signup'
    | '/user/topup'
    | '/user/wallet'
  id:
    | '__root__'
    | '/'
    | '/walkin'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/records'
    | '/admin/requests'
    | '/admin/revenue'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/site-details'
    | '/admin/sites'
    | '/admin/users'
    | '/user/active'
    | '/user/bills'
    | '/user/book'
    | '/user/complaints'
    | '/user/dashboard'
    | '/user/history'
    | '/user/login'
    | '/user/settings'
    | '/user/signup'
    | '/user/topup'
    | '/user/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WalkinRoute: typeof WalkinRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRecordsRoute: typeof AdminRecordsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteDetailsRoute: typeof AdminSiteDetailsRoute
  AdminSitesRoute: typeof AdminSitesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  UserActiveRoute: typeof UserActiveRoute
  UserBillsRoute: typeof UserBillsRoute
  UserBookRoute: typeof UserBookRoute
  UserComplaintsRoute: typeof UserComplaintsRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserHistoryRoute: typeof UserHistoryRoute
  UserLoginRoute: typeof UserLoginRoute
  UserSettingsRoute: typeof UserSettingsRoute
  UserSignupRoute: typeof UserSignupRoute
  UserTopupRoute: typeof UserTopupRoute
  UserWalletRoute: typeof UserWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/walkin': {
      id: '/walkin'
      path: '/walkin'
      fullPath: '/walkin'
      preLoaderRoute: typeof WalkinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/wallet': {
      id: '/user/wallet'
      path: '/user/wallet'
      fullPath: '/user/wallet'
      preLoaderRoute: typeof UserWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/topup': {
      id: '/user/topup'
      path: '/user/topup'
      fullPath: '/user/topup'
      preLoaderRoute: typeof UserTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/signup': {
      id: '/user/signup'
      path: '/user/signup'
      fullPath: '/user/signup'
      preLoaderRoute: typeof UserSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/login': {
      id: '/user/login'
      path: '/user/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/history': {
      id: '/user/history'
      path: '/user/history'
      fullPath: '/user/history'
      preLoaderRoute: typeof UserHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/complaints': {
      id: '/user/complaints'
      path: '/user/complaints'
      fullPath: '/user/complaints'
      preLoaderRoute: typeof UserComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/book': {
      id: '/user/book'
      path: '/user/book'
      fullPath: '/user/book'
      preLoaderRoute: typeof UserBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/bills': {
      id: '/user/bills'
      path: '/user/bills'
      fullPath: '/user/bills'
      preLoaderRoute: typeof UserBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/active': {
      id: '/user/active'
      path: '/user/active'
      fullPath: '/user/active'
      preLoaderRoute: typeof UserActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sites': {
      id: '/admin/sites'
      path: '/admin/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/site-details': {
      id: '/admin/site-details'
      path: '/admin/site-details'
      fullPath: '/admin/site-details'
      preLoaderRoute: typeof AdminSiteDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/admin/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/records': {
      id: '/admin/records'
      path: '/admin/records'
      fullPath: '/admin/records'
      preLoaderRoute: typeof AdminRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/admin/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WalkinRoute: WalkinRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRecordsRoute: AdminRecordsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteDetailsRoute: AdminSiteDetailsRoute,
  AdminSitesRoute: AdminSitesRoute,
  AdminUsersRoute: AdminUsersRoute,
  UserActiveRoute: UserActiveRoute,
  UserBillsRoute: UserBillsRoute,
  UserBookRoute: UserBookRoute,
  UserComplaintsRoute: UserComplaintsRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserHistoryRoute: UserHistoryRoute,
  UserLoginRoute: UserLoginRoute,
  UserSettingsRoute: UserSettingsRoute,
  UserSignupRoute: UserSignupRoute,
  UserTopupRoute: UserTopupRoute,
  UserWalletRoute: UserWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
